apiVersion: v1
kind: Service
metadata:
  name: {{ include "hextris.fullname" . }}
  labels:
    {{- include "hextris.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hextris.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}